name: CI

on: [push, pull_request]

jobs:
  paket:
    name: Paket test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: test
        uses: addnab/docker-run-action@v1
        with:
          image: joseluisq/paket
          shell: sh
          run: fish -c 'fish -v && paket --version && paket add joseluisq/gitnow' && fish -c 'gitnow -v'

  fisher:
    name: Fisher test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: test
        uses: addnab/docker-run-action@v1
        with:
          image: joseluisq/paket
          options: -v ${{ github.workspace }}:/gitnow
          shell: fish
          run: |
            apk add curl && curl -sL git.io/fisher | source && fish -v && fisher --version && fisher install /gitnow
            gitnow -v
